# Generated by Django 2.2.12 on 2020-04-21 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechapedido',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
