# Generated by Django 2.2.12 on 2020-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200421_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fechapedido',
            new_name='fechacreacionproducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='someslug'),
        ),
    ]
