# Generated by Django 2.2.12 on 2020-04-21 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200421_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechacreacionproducto',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Creación de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado / Deshabilitado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreproducto',
            field=models.CharField(max_length=30, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
