# Generated by Django 2.2.12 on 2020-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
