# Generated by Django 2.2.12 on 2020-04-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200419_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=20, verbose_name='Categoría ')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productosorden',
            options={'verbose_name': 'Producto Orden', 'verbose_name_plural': 'Productos Orden'},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_orden',
        ),
        migrations.AddField(
            model_name='orden',
            name='fechacontacto',
            field=models.DateField(auto_now=True, verbose_name='Fecha Pedido '),
        ),
        migrations.AlterField(
            model_name='orden',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellidos '),
        ),
        migrations.AlterField(
            model_name='orden',
            name='comentario',
            field=models.TextField(max_length=100, verbose_name='Comentario '),
        ),
        migrations.AlterField(
            model_name='orden',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo: '),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono',
            field=models.IntegerField(verbose_name='N° Teléfono '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombreproducto',
            field=models.CharField(max_length=30, verbose_name='Plato '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(verbose_name='Precio '),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Categoria'),
        ),
    ]
