# Generated by Django 2.2.12 on 2020-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_productos_categoriaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(default='añadir descripcion', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombreproducto',
            field=models.CharField(max_length=30, verbose_name='Producto '),
        ),
    ]
