# Generated by Django 2.2.12 on 2020-04-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_auto_20200421_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='item',
            field=models.ManyToManyField(to='inventario.Producto'),
        ),
    ]
