# Generated by Django 2.2.12 on 2020-04-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20200421_1803'),
        ('pedidos', '0013_auto_20200421_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden',
            new_name='Carrito',
        ),
        migrations.DeleteModel(
            name='ProductosOrden',
        ),
    ]
