# Generated by Django 2.2.12 on 2020-04-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20200421_1803'),
        ('pedidos', '0015_auto_20200421_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fechapedido',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='telefono',
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
