# Generated by Django 2.2.12 on 2020-04-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_auto_20200423_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='carritoitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CarritoItem'),
            preserve_default=False,
        ),
    ]
