# Generated by Django 2.2.12 on 2020-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_auto_20200424_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='carritoitem',
        ),
        migrations.AddField(
            model_name='carrito',
            name='carritoitem',
            field=models.ManyToManyField(to='pedidos.CarritoItem'),
        ),
    ]
