"""
Django settings for emecargoproject project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os #importa el sistema oiperativo

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6ih$q0uqsm^ej7scn_+k+)+c76b!0zi5i2id_a1$^k!ujy1*%5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #True cuando se esta desarrollando / False cuando se va a subir la app

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "farobelenccp@gmail.com"
EMAIL_HOST_PASSWORD = 'farobelen382'
EMAIL_PORT = '587'

ALLOWED_HOSTS = [] #[*] para subir la apgina tambien dento de las configuraciones

# Application definition
#modulos, trabajan de forma separada / separa la logica entre modulos para ser menos engorroso el codigo
INSTALLED_APPS = [ #aqui se instalaran las app's que se crearan en nuetro proyecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paginapp',
    'pedidos',
    'inventario',
    'orden',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', #seguridad al madnar POST y otras cosas TOKEN
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emecargoproject.urls' #rutas principales de todo el proyecto

TEMPLATES = [ #Django usa un sistema de platillas
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #directorios, la ruta donde le diremos donde alojaremos todos nuestros templates |  se le dice que en la carpeta Templates estaran los archivos html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emecargoproject.wsgi.application'#como se levantara la app o subir pagina


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#configuracion del CKEditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#https://www.youtube.com/watch?v=KqDYIAEAfpw&list=PLMbRqrU_kvbTGg_oUKXyWi63Mo9Yoot9K&index=28
STATICFILES_DIRS = (os.path.join(BASE_DIR), 'static') #donde se buscarán los archivos estaticos

MEDIA_URL = '/media/'
MEDIA_ROOT = (os.path.join(BASE_DIR), 'media')