# Generated by Django 2.2.9 on 2020-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('asunto', models.CharField(max_length=15)),
                ('mensaje', models.TextField(max_length=200)),
            ],
        ),
    ]
