# Generated by Django 2.2.9 on 2020-04-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
