# Generated by Django 2.2.9 on 2020-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0005_auto_20200405_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='asunto_id',
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(choices=[('CM', 'Comentario'), ('FT', 'Felicitaciones'), ('RC', 'Reclamo'), ('RS', 'Reserva'), ('PD', 'Pedido')], default='-', max_length=20),
        ),
        migrations.DeleteModel(
            name='Asuntos',
        ),
    ]
