# Generated by Django 2.2.9 on 2020-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0007_auto_20200405_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuntos',
            name='asuntos',
            field=models.CharField(choices=[('CM', 'Comentario'), ('FT', 'Felicitaciones'), ('RC', 'Reclamo'), ('RS', 'Reserva'), ('PD', 'Pedido')], default='CM', max_length=20),
        ),
    ]
