# Generated by Django 2.2.9 on 2020-04-05 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0008_auto_20200405_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginapp.Asuntos'),
        ),
    ]
