# Generated by Django 2.2.9 on 2020-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0010_auto_20200405_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuntos',
            name='asuntos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='asuntos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
