# Generated by Django 2.2.9 on 2020-04-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0011_auto_20200405_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asuntos',
            old_name='asuntos',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='asunto_id',
            new_name='asunto',
        ),
    ]
