# Generated by Django 2.2.9 on 2020-04-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0012_auto_20200405_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asuntos',
            options={'verbose_name': 'Asunto', 'verbose_name_plural': 'Asuntos'},
        ),
    ]
