# Generated by Django 2.2.9 on 2020-04-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0013_auto_20200405_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fechacontacto',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Recibo'),
        ),
    ]
