# Generated by Django 2.2.12 on 2020-04-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0016_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='texto',
            field=models.TextField(max_length=300, verbose_name='Primer Texto:'),
        ),
    ]
