# Generated by Django 2.2.12 on 2020-04-16 06:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0018_auto_20200416_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='historia/'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
