# Generated by Django 2.2.12 on 2020-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0019_auto_20200416_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='campo',
            field=models.CharField(default='no asignado', max_length=10),
        ),
    ]
