# Generated by Django 2.2.12 on 2020-04-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0020_historia_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechacontacto', models.DateField(auto_now_add=True, verbose_name='Fecha Pedido')),
                ('correo', models.EmailField(max_length=254)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginapp.categoriaProductos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginapp.Pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginapp.Productos')),
            ],
            options={
                'verbose_name': 'detallePedido',
                'verbose_name_plural': 'detallePedidos',
            },
        ),
    ]
