# Generated by Django 2.2.12 on 2020-04-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginapp', '0021_categoriaproductos_detallepedido_pedidos_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='categoriaProductos',
        ),
        migrations.DeleteModel(
            name='detallePedido',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
