# Generated by Django 2.2.12 on 2020-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0015_auto_20200421_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellidos ')),
                ('telefono', models.IntegerField(verbose_name='N° Teléfono ')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo: ')),
                ('fechapedido', models.DateField(auto_now=True, verbose_name='Fecha Pedido ')),
                ('carrito', models.ManyToManyField(to='pedidos.Carrito')),
            ],
            options={
                'verbose_name': 'Orden',
            },
        ),
    ]
