# Generated by Django 2.2.12 on 2020-04-24 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_auto_20200424_1902'),
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='carrito',
        ),
        migrations.AddField(
            model_name='orden',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Carrito'),
            preserve_default=False,
        ),
    ]
