# Generated by Django 2.2.12 on 2020-04-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20200424_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Carrito'),
        ),
    ]
